language: cpp
dist: zesty
compiler:
  - gcc
  - clang
before_install:
  - lsb_release -a
  - sudo apt-get update -qq
install:
  # gcc 6
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y -qq g++-6; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-6"; fi
  # clang 4.0
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y -qq clang++-4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-4"; fi
  # x0 dependencies
  - sudo apt-get install -y -qq make autoconf automake libtool pkg-config zlib1g-dev libssl-dev libpam-dev libpcre3-dev libfcgi-dev
script:
  - $CXX --version
  - ./autogen.sh --enable-proxy
  - make
  - ./xzero_test -v
branches:
  only:
    - master
notifications:
  recipients:
    - christian@parpart.family
  email:
    on_success: change
    on_failure: always
