language: generic
dist: trusty
sudo: required

services:
	- docker

# before_install:
# 	- eval "${MATRIX_EVAL}"

script:
  - $CXX --version
	- docker build -t x0 .

branches:
  only:
    - master

notifications:
  recipients:
    - christian@parpart.family
  email:
    on_success: change
    on_failure: always
