sudo: required
language: c++

services:
	- docker

# before_install:
# 	- eval "${MATRIX_EVAL}"

script:
	- docker build -t x0 .

# all branches
branches:
  only:
    - master
    - /.*/

notifications:
  recipients:
    - christian@parpart.family
  email:
    on_success: change
    on_failure: always
