language: cpp
dist: xenial
sudo: enabled
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r-test'
    packages:
    - clang++-4.0
    - g++-6.0
compiler:
  - gcc
  - clang
before_install:
  - lsb_release -a
  - sudo apt-get update -qq
install:
  # gcc
  - if [ "$CXX" == "g++" ]; then export CXX="g++-6"; fi
  # clang
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-4.0"; fi
  # x0 dependencies
  - sudo apt-get install -y -qq make autoconf automake libtool pkg-config zlib1g-dev libssl-dev libpam-dev libpcre3-dev libfcgi-dev
script:
  - $CXX --version
  - ./autogen.sh --enable-proxy
  - make
  - ./xzero_test -v
branches:
  only:
    - master
notifications:
  recipients:
    - christian@parpart.family
  email:
    on_success: change
    on_failure: always
