os:
  - linux

language: cpp

sudo: required

services:
	- docker

# before_install:
# 	- eval "${MATRIX_EVAL}"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang-5.0
      - clang++-5.0

script:
	- docker build -t x0 .

# all branches
branches:
  only:
    - master
    - /.*/

notifications:
  recipients:
    - christian@parpart.family
  email:
    on_success: change
    on_failure: always
