=head1 NAME

x0d - high performance HTTP web server

=head1 SYNOPSIS

x0d [B<-c> configfile] [B<-p> pidfile] [B<-u> user] [B<-g> group] [B<-i> path[,port]] [B<-hXGvy>]

=head1 DESCRIPTION

B<x0d> (pronounced: X-zero daemon) is a flexible, fast, and reasonable standards compliant
high performance HTTP/1.1 web server, written by Christian Parpart.

This man-page only documents B<x0d>-command line arguments

=head1 OPTIONS

=over 25

=item B<-c,--config=PATH>

Specifies a custom configuration file to load.

=item B<-h,--help>

Prints a short command line help.

=item B<-X,--no-fork>

Do not fork into background (/daemon-mode), detaching from the controlling
terminal.

=item B<-G,--guard>

Guard over the actual process by supervising its running state
and in case of emergency, restart it.

=item B<-p,--pid-file=PATH>

Specifies a path to a PID file to create, e.g. B</var/run/x0d/x0d.pid>.

=item B<-u,--user=NAME>

Specifies the user-name to drop privileges down to.
The process will also gain the user's standard-group If no group was
explicitely specified at command line.

=item B<-g,--group=NAME>

Specifies a group-name to drop group-privileges down to.
This overrides the standard-group associated with the specified user.

=item B<-i,--instant=PATH[,PORT]>

Runs B<x0d> in instant-mode, meaning, no configuration file is loaded nor
needed at all. B<x0d> will just serve a single document root B<PATH>
and listen for incoming requests on the specified port.

B<x0d> will by default listen on port 8080 if no port was specified.

=item B<--systemd>

Explicitely runs in systemd-mode, a new init-system, which is usually
detected by B<x0d> automatically but there might be reasons for you
to explicitely state that in the command line.

Do not pass this option until you have to.

=item B<-v,--version>

Prints version information for this software.

=item B<-y,--copyright>

Prints copyright information for this software.

=back

=head1 SIGNALS

=over 15

=item B<SIGTERM>

Fast and clean process shutdown (without waiting for the current requests to complete).
If the process does still not shutdown within 10 seconds (due to some silly plugins),
the event loops will be broken up to exit forcefully.

=item B<SIGINT>

Same as B<SIGTERM>.

=item B<SIGQUIT>

Graceful process shutdown (waiting for the current requests to complete).
If the process does not shutdown within 10 seconds, it will redirect to the
fast shutdown procedure instead.

=item B<SIGHUP>

Reexecutes a new binary with a newly loaded configuration file as a child process.

Before the child process is being executed, the parent process will suspend processing
any current connections and does not accept any new connections.

If the child process sends B<SIGQUIT> to its parent, it will gracefully shutdown.

If the child process somehow fails to start up (that is, exits, or times out
in calling back with a B<SIGQUIT> on success), the parent process kills the child instead
and resumes normal operation as if there has been no B<SIBHUP> sent to this process.

This method does not just reload into a new configuration file but also
executs into a new binary for that, and is though, suitable for on the fly executable upgrades.

=item B<SIGUSR1>

Reopen all log files (for logfile rotation) (TODO)

=back

=head1 HISTORY

The B<x0>-software development has been started in May 2009
by Christian Parpart with the goal to create a state-of-the-art
high performance HTTP web server and framework in modern C++.

=head1 LICENSE

B<x0d> and its standard plugins is licensed under GPL-3.

The B<x0 core framework> provided by the x0 project is licensed unter LGPL-3.

=head1 AUTHOR

B<x0d> (daemon, core framework, and plugins) is written by Christian Parpart <trapni@gentoo.org>

=head1 SEE ALSO

L<x0d.conf(5)>,
L<logroate(8)>,
L<spawn-fcgi(1)>
