.TH X0D.CONF "8" "2010-03-24" "" ""
.
.SH NAME
x0d.conf \- configuration file to x0d.
.
.SH SYNOPSIS
\fBlighttpd\fP [\fB\-ptDvVh\fP] \fB\-f\fP \fIconfigfile\fP [\fB\-m\fP \fImoduledir\fP]
.
.SH DESCRIPTION
\fBlighttpd\fP (pronounced 'lighty') is an advanced HTTP daemon that aims
to be secure, fast, compliant and very flexible.  It has been optimized for
high performance.  Its feature set includes, but is not limited to, FastCGI,
CGI, basic and digest HTTP authentication, output compression, URL rewriting.
.PP
This manual page only lists the command line arguments.  For details
on how to configure \fBlighttpd\fP and its modules see the files in the
doc-directory.

