
find_program(FLOW_CONFIG_EXECUTABLE NAMES flow-config DOC "flow-config executable")

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --cppflags
	OUTPUT_VARIABLE FLOW_CPPFLAGS
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --includedir
	OUTPUT_VARIABLE FLOW_INCLUDE_DIR
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --libdir
	OUTPUT_VARIABLE FLOW_LIBRARY_DIR
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --ldflags
	OUTPUT_VARIABLE FLOW_LDFLAGS
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --libs
	OUTPUT_VARIABLE FLOW_LIBRARIES
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${FLOW_CONFIG_EXECUTABLE} --version
	OUTPUT_VARIABLE FLOW_VERSION
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "FLOW config: " ${FLOW_CONFIG_EXECUTABLE})
message(STATUS "FLOW cppflags: " ${FLOW_CPPFLAGS})
message(STATUS "FLOW ldflags: " ${FLOW_LDFLAGS})
message(STATUS "FLOW library dir: " ${FLOW_LIBRARY_DIR})
message(STATUS "FLOW include dir: " ${FLOW_INCLUDE_DIR})
message(STATUS "FLOW libraries: " ${FLOW_LIBRARIES})
message(STATUS "FLOW version: " ${FLOW_VERSION})
